version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_scraping
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./data:/var/lib/mysql # Maps a volume for data persistence
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Mounts the init.sql script
    ports:
      - '3306:3306' # Maps the MySQL port inside the container to the host
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:3000' # Maps the NestJS application port inside the container to the host